version: '3.4'

services:
  linuxbotv2:
    image: linuxbotv2
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
